version: '3'

services:
  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=wordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    volumes:
      - dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app-network
  wordpress:
    depends_on:
      - db
    image: wordpress:5.1.1-fpm-alpine
    container_name: wordpress
    restart: unless-stopped
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - app-network
  nginx:
    depends_on:
      - wordpress
    image: nginx:1.15.12-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - wordpress:/var/www/html
      - nginx-conf:/etc/nginx/conf.d
    networks:
      - app-network

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/heat/Documents/containers/ww-wordpress/wordpress
      o: bind
  nginx-conf:
    driver: local
    driver_opts:
      type: none
      device: /home/heat/Documents/containers/ww-wordpress/nginx-conf
      o: bind
  dbdata:

networks:
  app-network:
    driver: bridge
